language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y gettext nasm
- chmod -R 777 *
script:
- mkdir build target
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=../target -DBUILD_ROK4=TRUE -DBUILD_BE4=FALSE -DBUILD_DOC=FALSE
  -DUNITTEST=false -DDEBUG_BUILD=FALSE
- make package
deploy:
  provider: releases
  api_key:
    secure: iBvpbuyzyk/ReIli72fki1cvUTffXc/kgu3zcg8rlYk00BNWe1Maf9ziNo/0SWRu5vHQnKyipd6/dQaXgBF+sjBg2yTTSMumOHUnMY3/Mu7m2Id/iqAM+MuprQH+EQjFuOMUUdcXWPnm0RkHQmXF624ckt+zmol/pwjB1ag1tK8=
  file: build/Rok4*
  on:
    repo: rok4/rok4
    tags: true
