language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gettext nasm
  - chmod -R 777 *
script:
  - mkdir build target
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DBUILD_ROK4=TRUE -DBUILD_BE4=FALSE -DBUILD_DOC=FALSE -DUNITTEST=false -DDEBUG_BUILD=FALSE
  - make package
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  file: "Rok4*"
  skip_cleanup: true
  on:
    tags: true
